# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  # Python
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    groups:
      python:
        patterns:
          - "*"

  # Rust
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    groups:
      rust:
        patterns:
          - "*"

  # Rust (PyO3)
  - package-ecosystem: "cargo"
    directory: "/python-pyo3"
    schedule:
      interval: "weekly"
    groups:
      pyo3:
        patterns:
          - "*"

  # Go
  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: "weekly"
    groups:
      go:
        patterns:
          - "*"

  # Node
  - package-ecosystem: npm
    directory: /nodejs
    schedule:
      interval: "weekly"
    groups:
      node:
        patterns:
          - "*"
