[package]
name = "nitor-vault-pyo3"
version = "0.1.0"
edition = "2021"

[lib]
name = "nitor_vault"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.91"
nitor-vault = { path = "../rust" }
pyo3 = "0.22.0"
tokio = "1.41.0"
