[package]
name = "nitor-vault-pyo3"
version = "0.1.0"
edition = "2021"

[lib]
name = "nvault"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
nitor-vault = { path = "../rust" }
tokio = "1.41.0"
anyhow = "1.0.91"
