[package]
name = "nitor-vault"
version = "0.5.2"
edition = "2021"
description = "Encrypted AWS key-value storage utility."
license = "Apache-2.0"
repository = "https://github.com/nitorcreations/vault"
keywords = ["secrets", "s3", "cli"]
authors = [
  "Kalle Ahlström <kalle.ahlstrom@nitor.com",
  "Akseli Lukkarila <akseli.lukkarila@nitor.com>",
]

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.81"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-cloudformation = "1.17.0"
aws-sdk-kms = "1.15.0"
aws-sdk-s3 = "1.17.0"
base64 = "0.22.0"
clap = { version = "4.5.3", features = ["derive", "env"] }
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
thiserror = "1.0.58"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "vault"
path = "src/main.rs"

[profile.release]
lto = true
