[package]
name = "nitor-vault"
version = "0.1.3"
edition = "2021"
authors = ["Kalle Ahlström <kalle.ahlstrom@nitor.com", "Akseli Lukkarila <akseli.lukkarila@nitor.com>"]
description = "Encrypted AWS key-value storage"
license ="Apache-2.0"
repository = "https://github.com/nitorcreations/vault"
keywords = ["secrets","s3"]


[dependencies]
tokio = { version = "1", features = ["full"] }
aes-gcm = "0.10.1"
aws-config = "0.54.1"
aws-sdk-cloudformation = "0.24.0"
aws-sdk-kms = "0.24.0"
aws-sdk-s3 = "0.24.0"
aws-sdk-sts = "0.24.0"
base64 = "0.21.0"
clap = { version = "4.1.8", features = ["derive"] }
rand = "0.8.5"
serde = "1.0.152"
serde_json="1.0"

[[bin]]
name = "vault"
path = "src/main.rs"
