[package]
name = "nitor-vault"
version = "0.4.1"
edition = "2021"
authors = [
  "Kalle Ahlström <kalle.ahlstrom@nitor.com",
  "Akseli Lukkarila <akseli.lukkarila@nitor.com>",
]
description = "Encrypted AWS key-value storage"
license = "Apache-2.0"
repository = "https://github.com/nitorcreations/vault"
keywords = ["secrets", "s3"]

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.79"
aws-config = { version = "1.1.2", features = ["behavior-version-latest"] }
aws-sdk-cloudformation = "1.11.0"
aws-sdk-kms = "1.10.0"
aws-sdk-s3 = "1.12.0"
base64 = "0.21.5"
clap = { version = "4.4.13", features = ["derive", "env"] }
rand = "0.8.5"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.56"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "vault"
path = "src/main.rs"
