[package]
name = "nitor-vault"
version = "0.2.0"
edition = "2021"
authors = ["Kalle Ahlström <kalle.ahlstrom@nitor.com", "Akseli Lukkarila <akseli.lukkarila@nitor.com>"]
description = "Encrypted AWS key-value storage"
license = "Apache-2.0"
repository = "https://github.com/nitorcreations/vault"
keywords = ["secrets","s3"]

[dependencies]
aes-gcm = "0.10.1"
anyhow = "1.0.71"
aws-config = "0.55.1"
aws-sdk-cloudformation = "0.28.0"
aws-sdk-kms = "0.26.0"
aws-sdk-s3 = "0.28.0"
aws-sdk-sts = "0.28.0"
base64 = "0.21.0"
clap = { version = "4.2.5", features = ["derive"] }
rand = "0.8.5"
serde = "1.0.160"
serde_json="1.0"
thiserror = "1.0.40"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "vault"
path = "src/main.rs"
