[package]
name = "nitor-vault"
version = "0.6.1"
edition = "2021"
description = "Encrypted AWS key-value storage utility."
license = "Apache-2.0"
repository = "https://github.com/nitorcreations/vault"
keywords = ["secrets", "s3", "cli"]
authors = [
    "Kalle Ahlström <kalle.ahlstrom@nitor.com",
    "Akseli Lukkarila <akseli.lukkarila@nitor.com>",
]

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.82"
aws-config = { version = "1.1.8", features = ["behavior-version-latest"] }
aws-sdk-cloudformation = "1.21.1"
aws-sdk-kms = "1.18.0"
aws-sdk-s3 = "1.20.0"
base64 = "0.22.1"
clap = { version = "4.5.4", features = ["derive", "env"] }
colored = "2.1.0"
rand = "0.8.5"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["full"] }

[[bin]]
name = "vault"
path = "src/main.rs"

[profile.release]
lto = true
