name: flake8

# Run either when pushing directly to main/master or in a PR targeting main/master
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "**.py"

# https://github.com/py-actions/flake8
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Python-lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: flake8 lint
        uses: py-actions/flake8@v2
        with:
          path: python
          args: "--config python/setup.cfg"
