name: Go

on:
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "go/go.mod"
      - "go/go.sum"
      - ".github/workflows/go.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
      - "go/go.mod"
      - "go/go.sum"
      - ".github/workflows/go.yml"

# Cancel previous runs for PRs but not pushes to main
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'main' || github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.22.x"
          cache-dependency-path: go/go.sum

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test
