name: Integration Tests between the different implementations

# Run either when pushing directly to main/master or in a PR targeting main/master
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.go"
      - "go/go.mod"
      - "go/go.sum"
      - ".github/workflows/integration.yml"
  pull_request:
    branches:
      - master
      - main
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VAULT_STACK: nitor-vault-integration-testing
    strategy:
      matrix:
        lang: [go, rust]
    defaults:
      run:
        working-directory: ${{matrix.lang}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        if: ${{ matrix.lang == 'rust'}}
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.7.0
        if: ${{ matrix.lang == 'rust'}}
        with:
          cache-directories: rust
      - uses: actions/setup-go@v4
        if: ${{ matrix.lang == 'go'}}
        with:
          go-version: ">=1.21.0"
          cache-dependency-path: go/go.sum
      - name: Run build script for compiled languages
        if: ${{ hashFiles(join(matrix.lang,'build.sh')) != '' }}
        run: "./build.sh"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.lang}}-vault
          path: ${{matrix.lang}}/vault
  create_keys:
    needs: build
    runs-on: ubuntu-latest
    env:
      VAULT_STACK: nitor-vault-integration-testing

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_CI_ROLE}}
          aws-region: eu-west-1
      - uses: actions/checkout@v4
      - name: Download reports' artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install python vault to path
        run: python -m pip install .
        working-directory: python
      - name: run version for all version
        run: |
          vault --version
          bin/go-vault --version
          bin/rust-vault --version
