name: Python pip

on:
  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/pip.yml"
      - "python/requirements.txt"
  pull_request:
    paths:
      - ".github/workflows/pip.yml"
      - "python/requirements.txt"

# Cancel previous runs for PRs but not pushes to main
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true


jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "python/requirements.txt"
