name: Go Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    if: startsWith(github.ref, 'refs/tags/go')
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: "go build"
        run: go/build.sh
        env:
          GOARCH: ${{matrix.goarch}}
          GOOS: ${{matrix.goos}}
      - uses: Shopify/upload-to-release@v2.0.0
        with:
          name: vault-${{matrix.goos}}-${{matrix.goarch}}-${{github.ref_name}}${{matrix.goos == 'windows' && '.exe' ||''}}
          path: go/vault
          repo-token: ${{ secrets.GITHUB_TOKEN }}
