name: Python ruff

# Run either when pushing directly to main/master or in a PR targeting main/master
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.py"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "**.py"

# https://github.com/chartboost/ruff-action
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./python"
