name: Rust

on:
  push:
    branches:
      - master
      - main
    paths:
      - ".github/workflows/rust.yml"
      - "**.rs"
      - "Cargo.lock"
      - "Cargo.toml"
      - "python-pyo3/Cargo.toml"
      - "rust/Cargo.toml"
  pull_request:
    paths:
      - ".github/workflows/rust.yml"
      - "**.rs"
      - "Cargo.lock"
      - "Cargo.toml"
      - "python-pyo3/Cargo.toml"
      - "rust/Cargo.toml"

# Cancel previous runs for PRs but not pushes to main
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - uses: Swatinem/rust-cache@v2.8.0

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test --no-fail-fast

      - name: Lint
        run: cargo clippy -- -Dwarnings

  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --check --verbose
